version: "3.7"
services:
  app:
    image: bastyje/odwsi-angular:1.0
    restart: always
    networks:
      notepad-net:
        ipv4_address: 10.0.0.2
  api:
    image: bastyje/odwsi-net:1.0
    networks:
      notepad-net:
        ipv4_address: 10.0.0.3
      notepad-internal-net:
        ipv4_address: 10.0.1.3
    working_dir: /App
  mssql:
    image: bastyje/odwsi-database:1.0
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    networks:
      notepad-internal-net:
        ipv4_address: 10.0.1.2
networks:
  notepad-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
  notepad-internal-net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.1.0/29
